### ISSUE TITLE
Login/Register not working

### ISSUE THREAD

**Issue by Bartek532** [leandertolksdorf/remarkable-rss#19]
When I try to register message says: "This user already exists":
![image](https://user-images.githubusercontent.com/57185551/160412669-5682f6ae-13f5-4ddf-8900-c0b5abdd511c.png)

but when I try to sign it says, that "This user doesn't exist": 
![image](https://user-images.githubusercontent.com/57185551/160412767-dfa36592-d569-4dfd-a095-240c6615296f.png)

**Comment by elte0** [comment]
Thanks for reporting! I saw you forked the project. Do you want to work on this?

**Comment by Bartek532** [comment]
Yeah, sure! But in this case, I think it's a problem with database, so I can't do much :( However, I have a couple of ideas to improve this app so maybe should I open more issues or do some pull requests?

**Comment by Bartek532** [comment]
Exactly, when I tried with my own MongoDB it's working fine. So you should check your database :)

**Comment by elte0** [comment]
Ok, thanks for checking. Will try to find the problem.

**Comment by elte0** [comment]
@Bartek532 
There were indeed some indexing errors in MongoDB.
I just dropped the indexes of the users collection in the db, which seems to be the solution. 
Can you try registering again?
