### ISSUE TITLE
Installation progress

### ISSUE THREAD

**Issue by Reacien** [leandertolksdorf/remarkable-rss#23]
I was wondering if there is a tutorial on how to set this up exactly on my remarkable 2?

**Comment by elte0** [comment]
This is not installable on reMarkable. It's a web app that connects with your reMarkable cloud. See [remarkable-rss.farbig.media/](https://remarkable-rss.farbig.media/)

**Comment by Reacien** [comment]
So it'll send any new rss feed post to my remarkable through the cloud?
